[package]
name = "proc-upload"
version = "0.1.0"
authors = ["Yuhao Fang <fangyuhao@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.11"
syn = "0.15.29"